config/routes.rb
TestMongoId::Application.routes.draw do

  post "/prices/randomize", to: "prices#randomize", as: "randomize_prices"
  get "/prices/delete_all", to: "prices#delete_all", as: "delete_all"
  get "/prices/autoload", to: "prices#autoload", as: "autoload"
  get "/prices/reorder_missed", to: "prices#reorder_missed", as: "reorder_missed"
  get "/prices/next", to: "prices#next", as: "next"
  get "/prices/disable/:id", to: "prices#disable", as: "disable"
  get "/prices/list", to: "prices#list", as: "list"
  
  resources :prices

  root "static_pages#home"

end

app/models/log.rb
class Log
  include Mongoid::Document
  include Mongoid::Timestamps

  def self.new_log
    l = Log.new
    l.save
  end
end

app/models/price.rb
class Price
  include Mongoid::Document

  default_scope ->{ asc(:time) }
  scope :enabled, ->{where(enabled: true)}
  scope :disabled, ->{where(enabled: false)}

  field :type, type: String
  field :enabled, type: Mongoid::Boolean
  field :time, type: Time


  def self.randomize type, number, init_time, end_time
    init_time = parse_time(init_time)
    end_time  = parse_time(end_time)

    number.times do 
      FactoryGirl.create(:price, type: type, time: init_time + rand(0..elapsed_seconds(init_time, end_time)))
    end
  end

  def self.elapsed_seconds init_time, end_time
    (end_time - init_time).to_i
  end

  def self.parse_time time_string
    init_hour = time_string.split(':')[0].to_i
    init_minute = time_string.split(':')[1].to_i
    Time.now.change({ hour: init_hour, min: init_minute, sec: 0 })
  end

  def self.next
    enabled.first && enabled.first.open? ? enabled.first : FactoryGirl.build(:price, :nothing)
  end

  def open?
    (Time.now - time) >= 0
  end

  def editable?
    enabled?
  end

  def self.autoload
    PRICES.each do |price|
      randomize(price, NUMBERS[price], INIT_TIMES[price], END_TIMES[price])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy, :disable]

  # GET /prices
  def index
    @prices = Price.all
  end

  # GET /prices/1/edit
  def edit
  end

  def list
    respond_to do |format|
      format.json {render json: PRICES}
    end
  end

  def randomize
    Price.randomize params[:type], params[:number].to_i, params[:init_time], params[:end_time]
    redirect_to prices_path(params), notice: 'Prices was successfully randomized.'  
  end

  def next
    @price = Price.next
    Log.new_log
    respond_to do |format|
      format.json {render json: @price}
    end
  end

  def disable
    @price.enabled = false
    @price.save!
    render json: @price
  end

  # PATCH/PUT /prices/1
  def update
    if @price.update(price_params)
      redirect_to @price, notice: 'Price was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /prices/1
  def destroy
    @price.destroy
    redirect_to prices_url, notice: 'Price was successfully destroyed.'
  end

  def delete_all
    Price.destroy_all
    redirect_to prices_path, notice: 'Prices were successfully destroyed.'
  end

  def autoload
    Price.autoload
    redirect_to prices_path, notice: 'Prices were loaded.'
  end

  def reorder_missed
    Price.reorder_missed
    redirect_to prices_path, notice: 'Prices were successfully reordered.'
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def price_params
      params.require(:price).permit(:type, :enabled, :time)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to prices_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper

  def price_options
    options = []
    PRICES.each do |price|
      options << [pretty_print(price), price]
    end
    options
  end

  def pretty_print name
    name.gsub("_", " ").titleize
  end

  def price_stats name
   str = ""
   str += pretty_print(name)
   str += ": " 
   str += Price.where(type: name, enabled: true).count.to_s
   str += "/" 
   str += Price.where(type: name).count.to_s
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Price Manager</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section id="messages">
  <% if flash[:notice] %>
    <div id="notice" class="alert alert-success flash"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:warning] %>
    <div id="warning" class="alert alert-warning flash"><%= flash[:warning] %></div>
  <% end %>

  <% if flash[:error] %>
    <div id="error" class="alert alert-danger flash"><%= flash[:error] %></div>
  <% end %>
</section>

<%= yield %>

</body>
</html>

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/_randomize_form.html.erb
<%= form_tag randomize_prices_path do %>
  <%= label_tag("Type:") %>
  <%= select_tag :type, options_for_select(price_options) %>

  <%= label_tag("Number:") %>
  <%= select_tag :number, options_for_select((0..100).step(1).to_a.map{|s| ["#{s}", s]}) %>

  <%= label_tag("Init:") %>
 <%= text_field_tag('init_time', params[:init_time]) %>

  <%= label_tag("End:") %>
 <%= text_field_tag('end_time', params[:end_time]) %>
<br>

  <%= submit_tag("Randomize") %>
<% end %>

<script>
  $('#init_time').timepicker({
    showMeridian: false
  });
  $('#end_time').timepicker({
    showMeridian: false
  });
</script>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h5> Local time: <%= Time.now.localtime.strftime("%H:%M:%S") %> </h5>

<div class="row">

  <div class="span3">

    <table id="prices_list">
        <tbody>
        <% @prices.each do |price| %>
          <tr id="price_<%= price.id %>"  class="<%= price.enabled? ? 'enabled' : 'disabled' %> <%= price.type %> <%= "open" if price.open? %>">
            <td><%= pretty_print(price.type) %> </td>
            <td><%= price.time.localtime.strftime("%H:%M:%S") %></td>

            <td><%= link_to 'Delete', price, method: :delete, data: { confirm: 'Are you sure?' } if price.editable? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <div class="span3">
    <div id="info">
      <h5>Remaining prices / Total prices</h5>
      <ul>
        <li>Total: <%= Price.enabled.count %>/<%= Price.all.count %></li>
        <% PRICES.each do |price| %>
          <li><%= price_stats(price) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="span6">
    <%= render "randomize_form" %>
    
    <%= link_to 'Delete all', delete_all_path, data: { confirm: 'Are you sure?' } %>
    <br>
    <%= link_to 'Autoload', autoload_path %>

  </div>
</div>








<style type="text/css">
.disabled{
  text-decoration: line-through;
  color:red;
}
.enabled.open{
  color: green;
  font-weight: bolder;
}
.enabled{
  color: gray;
}

</style>

app/views/static_pages/home.html.erb
<%= link_to "Price Manager", prices_path %>